const { callOllama } = require("./ollamaHelper");
const { parsePrompt } = require("./parser");
const { generateSchedule } = require("./scheduler");
const { analyzeScheduleQuality, detectConflicts, suggestOptimizations, costAnalysis } = require("./aiScheduleAnalyzer");
const { recordTeacherPreferences, globalLearning } = require("./aiLearningSystem");

async function autoGenerateSchedule(userPrompt) {
  console.log("🤖 Starting AI Auto-Generation...");
  
  try {
    // ============= PHASE 1: PARSE NATURAL LANGUAGE WITH EXISTING PARSER =============
    console.log("📝 Phase 1: Parsing natural language input...");
    
    let parsed;
    try {
      parsed = await parsePrompt(userPrompt);
    } catch (e) {
      console.error("Parser error:", e.message);
      return {
        success: false,
        error: "Could not parse scheduling request",
        suggestion: "Try describing courses like: 'Dr. Smith teaches Python to 80 students, 3 hours/week, prefers mornings'",
      };
    }

    if (!parsed.courses || parsed.courses.length === 0) {
      return {
        success: false,
        error: "No courses found in description",
        suggestion: "Please include at least one course with: course name, faculty name, hours per week",
      };
    }

    console.log(`✅ Parsed ${parsed.courses.length} courses successfully`);

    // ============= PHASE 2: GENERATE SCHEDULE =============
    console.log("📅 Phase 2: Generating optimized schedule...");
    const schedule = generateSchedule(parsed);

    if (!schedule.assignments || schedule.assignments.length === 0) {
      return {
        success: false,
        error: "Failed to generate schedule - possible constraint conflicts",
        details: {
          coursesRequested: parsed.courses.length,
          roomsAvailable: parsed.rooms?.length || 0,
          conflicts: schedule.conflicts?.length || 0,
        },
        recovery: "Try with fewer courses or more flexible preferences",
      };
    }

    console.log(`✅ Generated schedule with ${schedule.assignments.length} assignments`);

    // ============= RETURN IMMEDIATELY WITH SCHEDULE (Analysis in background) =============
    // This gives user instant feedback while analysis/learning continues in background
    const response = {
      success: true,
      schedule: schedule,
      parsed: parsed,
      autoGenerated: {
        coursesProcessed: parsed.courses.length,
        coursesScheduled: schedule.assignments?.length || 0,
        roomsAssigned: new Set(schedule.assignments?.map(a => a.room)).size,
        teachersAssigned: new Set(schedule.assignments?.map(a => a.faculty)).size,
      },
      status: "Generated - Analysis in progress",
      readyToUse: true,
    };

    // ============= RUN ANALYSIS IN BACKGROUND (Don't await) =============
    // This allows immediate response to user while expensive operations continue
    runBackgroundAnalysis(schedule, parsed).catch(e => {
      console.error("Background analysis error:", e.message);
    });

    return response;
  } catch (error) {
    console.error("❌ Error in auto-generation:", error.message);
    return {
      success: false,
      error: "Auto-generation failed: " + error.message,
    };
  }
}

// Background analysis that doesn't block the response
async function runBackgroundAnalysis(schedule, parsed) {
  console.log("🔍 Phase 3: Analyzing schedule in background...");
  try {
    const quality = await analyzeScheduleQuality(schedule, parsed);
    const conflicts = await detectConflicts(schedule, parsed);
    
    console.log(`✅ Analysis complete - Quality Score: ${quality?.overallScore || 0}/100`);

    // Record learning (optional, non-critical)
    console.log("📚 Phase 4: Recording learning data...");
    const uniqueFaculty = new Set(parsed.courses?.map(c => c.faculty).filter(Boolean) || []);
    for (const faculty of uniqueFaculty) {
      try {
        const facultyAssignments = schedule.assignments?.filter(a => a.faculty === faculty) || [];
        if (facultyAssignments.length > 0) {
          await recordTeacherPreferences(faculty, {
            assignments: facultyAssignments,
            qualityScore: quality?.overallScore || 0,
            timestamp: new Date().toISOString(),
          });
        }
      } catch (e) {
        console.warn(`Warning recording preferences for ${faculty}:`, e.message);
      }
    }

    console.log("✅ Background analysis complete");
  } catch (error) {
    console.error("Background analysis failed:", error.message);
  }
}

async function autoOptimizeSchedule(existingSchedule, parsed) {
  console.log("🔧 Starting auto-optimization...");

  try {
    const currentQuality = await analyzeScheduleQuality(existingSchedule, parsed);
    const conflicts = await detectConflicts(existingSchedule, parsed);
    const optimizations = await suggestOptimizations(existingSchedule, parsed);

    return {
      success: true,
      originalQuality: currentQuality.overallScore,
      analysis: {
        quality: currentQuality,
        conflicts: conflicts,
        optimizations: optimizations,
      },
      readyForImplementation: optimizations.immediateOptimizations?.length > 0,
      recommendations: generateRecommendations(currentQuality, conflicts, optimizations),
    };
  } catch (error) {
    console.error("Error analyzing schedule:", error.message);
    return {
      success: false,
      error: error.message,
    };
  }
}

// Helper: Generate actionable recommendations
function generateRecommendations(quality, conflicts, optimizations) {
  const recommendations = [];

  if (quality.overallScore < 70) {
    if (optimizations?.structuralImprovements?.[0]) {
      recommendations.push({
        priority: "high",
        action: "Review schedule structure",
        reason: "Quality score below optimal",
        suggestion: optimizations.structuralImprovements[0]?.description,
      });
    }
  }

  if (conflicts?.criticalIssues?.length > 0) {
    recommendations.push({
      priority: "critical",
      action: "Resolve conflicts",
      reason: `${conflicts.criticalIssues.length} critical issue(s) detected`,
      details: conflicts.criticalIssues.slice(0, 2).map(i => i.issue),
    });
  }

  if (optimizations?.immediateOptimizations?.length > 0) {
    recommendations.push({
      priority: "medium",
      action: "Apply quick wins",
      reason: "Immediate optimizations available",
      options: optimizations.immediateOptimizations.slice(0, 3).map(o => ({
        action: o.description,
        expectedGain: o.expectedImprovement,
      })),
    });
  }

  return recommendations.slice(0, 5);
}

module.exports = {
  autoGenerateSchedule,
  autoOptimizeSchedule,
};
