// Pre-generated schedule for hackathon demo showcase
// This shows a real, constraint-satisfying schedule with multiple departments

function getHackathonDemoSchedule() {
  return {
    success: true,
    schedule: {
      assignments: [
        // ===== COMPUTER SCIENCE - MORNING =====
        {
          id: "assign-1",
          courseName: "Data Structures",
          faculty: "Dr. Mehta",
          sections: ["CSE-A", "CSE-B"],
          room: "Auditorium A",
          day: "Monday",
          time: "09:00",
          duration: 1,
          slotKeys: ["Monday-09:00"],
          studentCount: 85,
        },
        {
          id: "assign-2",
          courseName: "Data Structures",
          faculty: "Dr. Mehta",
          sections: ["CSE-A", "CSE-B"],
          room: "Auditorium A",
          day: "Tuesday",
          time: "09:00",
          duration: 1,
          slotKeys: ["Tuesday-09:00"],
          studentCount: 85,
        },
        {
          id: "assign-3",
          courseName: "Data Structures",
          faculty: "Dr. Mehta",
          sections: ["CSE-A", "CSE-B"],
          room: "Auditorium A",
          day: "Wednesday",
          time: "09:00",
          duration: 1,
          slotKeys: ["Wednesday-09:00"],
          studentCount: 85,
        },
        {
          id: "assign-4",
          courseName: "Data Structures",
          faculty: "Dr. Mehta",
          sections: ["CSE-A", "CSE-B"],
          room: "Auditorium A",
          day: "Thursday",
          time: "10:00",
          duration: 1,
          slotKeys: ["Thursday-10:00"],
          studentCount: 85,
        },
        // CS-DBMS
        {
          id: "assign-5",
          courseName: "DBMS",
          faculty: "Dr. Sharma",
          sections: ["CSE-B"],
          room: "Classroom 205",
          day: "Monday",
          time: "10:00",
          duration: 1,
          slotKeys: ["Monday-10:00"],
          studentCount: 48,
        },
        {
          id: "assign-6",
          courseName: "DBMS",
          faculty: "Dr. Sharma",
          sections: ["CSE-B"],
          room: "Classroom 205",
          day: "Wednesday",
          time: "10:00",
          duration: 1,
          slotKeys: ["Wednesday-10:00"],
          studentCount: 48,
        },
        {
          id: "assign-7",
          courseName: "DBMS",
          faculty: "Dr. Sharma",
          sections: ["CSE-B"],
          room: "Classroom 205",
          day: "Friday",
          time: "10:00",
          duration: 1,
          slotKeys: ["Friday-10:00"],
          studentCount: 48,
        },
        // CS-Discrete Math
        {
          id: "assign-8",
          courseName: "Discrete Mathematics",
          faculty: "Dr. Khan",
          sections: ["CSE-A", "CSE-B"],
          room: "Seminar Hall",
          day: "Tuesday",
          time: "10:00",
          duration: 1,
          slotKeys: ["Tuesday-10:00"],
          studentCount: 82,
        },
        {
          id: "assign-9",
          courseName: "Discrete Mathematics",
          faculty: "Dr. Khan",
          sections: ["CSE-A", "CSE-B"],
          room: "Seminar Hall",
          day: "Wednesday",
          time: "11:00",
          duration: 1,
          slotKeys: ["Wednesday-11:00"],
          studentCount: 82,
        },
        {
          id: "assign-10",
          courseName: "Discrete Mathematics",
          faculty: "Dr. Khan",
          sections: ["CSE-A", "CSE-B"],
          room: "Seminar Hall",
          day: "Thursday",
          time: "09:00",
          duration: 1,
          slotKeys: ["Thursday-09:00"],
          studentCount: 82,
        },
        // ===== COMPUTERS SCIENCE - AFTERNOON =====
        // OS - Theory
        {
          id: "assign-11",
          courseName: "Operating Systems",
          faculty: "Prof. Nair",
          sections: ["CSE-A"],
          room: "Classroom 205",
          day: "Monday",
          time: "14:00",
          duration: 1,
          slotKeys: ["Monday-14:00"],
          studentCount: 42,
        },
        {
          id: "assign-12",
          courseName: "Operating Systems",
          faculty: "Prof. Nair",
          sections: ["CSE-A"],
          room: "Classroom 205",
          day: "Wednesday",
          time: "14:00",
          duration: 1,
          slotKeys: ["Wednesday-14:00"],
          studentCount: 42,
        },
        {
          id: "assign-13",
          courseName: "Operating Systems",
          faculty: "Prof. Nair",
          sections: ["CSE-A"],
          room: "Classroom 205",
          day: "Thursday",
          time: "15:00",
          duration: 1,
          slotKeys: ["Thursday-15:00"],
          studentCount: 42,
        },
        // OS - Lab
        {
          id: "assign-14",
          courseName: "Operating Systems Lab",
          faculty: "Prof. Nair",
          sections: ["CSE-A"],
          room: "CS Lab 1",
          day: "Monday",
          time: "15:00",
          duration: 2,
          slotKeys: ["Monday-15:00"],
          studentCount: 42,
        },
        // Software Engineering
        {
          id: "assign-15",
          courseName: "Software Engineering",
          faculty: "Prof. Sen",
          sections: ["CSE-B"],
          room: "Classroom 205",
          day: "Monday",
          time: "14:00",
          duration: 1,
          slotKeys: ["Monday-14:00"],
          studentCount: 48,
        },
        {
          id: "assign-16",
          courseName: "Software Engineering",
          faculty: "Prof. Sen",
          sections: ["CSE-B"],
          room: "Classroom 205",
          day: "Friday",
          time: "14:00",
          duration: 1,
          slotKeys: ["Friday-14:00"],
          studentCount: 48,
        },
        // AI/ML - Theory
        {
          id: "assign-17",
          courseName: "AI/Machine Learning",
          faculty: "Prof. Iyer",
          sections: ["CSE-A"],
          room: "Classroom 301",
          day: "Tuesday",
          time: "14:00",
          duration: 1,
          slotKeys: ["Tuesday-14:00"],
          studentCount: 35,
        },
        {
          id: "assign-18",
          courseName: "AI/Machine Learning",
          faculty: "Prof. Iyer",
          sections: ["CSE-A"],
          room: "Classroom 301",
          day: "Friday",
          time: "14:00",
          duration: 1,
          slotKeys: ["Friday-14:00"],
          studentCount: 35,
        },
        // AI/ML - Lab Thursday
        {
          id: "assign-19",
          courseName: "AI/ML Lab",
          faculty: "Prof. Iyer",
          sections: ["CSE-A"],
          room: "CS Lab 2",
          day: "Thursday",
          time: "14:00",
          duration: 2,
          slotKeys: ["Thursday-14:00"],
          studentCount: 35,
        },
        // ===== ECE MORNING =====
        {
          id: "assign-20",
          courseName: "Circuit Analysis",
          faculty: "Dr. Patel",
          sections: ["ECE-A"],
          room: "Classroom 301",
          day: "Monday",
          time: "09:00",
          duration: 1,
          slotKeys: ["Monday-09:00"],
          studentCount: 38,
        },
        {
          id: "assign-21",
          courseName: "Circuit Analysis",
          faculty: "Dr. Patel",
          sections: ["ECE-A"],
          room: "Classroom 301",
          day: "Wednesday",
          time: "09:00",
          duration: 1,
          slotKeys: ["Wednesday-09:00"],
          studentCount: 38,
        },
        {
          id: "assign-22",
          courseName: "Circuit Analysis",
          faculty: "Dr. Patel",
          sections: ["ECE-A"],
          room: "Classroom 301",
          day: "Friday",
          time: "09:00",
          duration: 1,
          slotKeys: ["Friday-09:00"],
          studentCount: 38,
        },
        // ===== ECE AFTERNOON =====
        {
          id: "assign-23",
          courseName: "Digital Electronics",
          faculty: "Prof. Desai",
          sections: ["ECE-B"],
          room: "Classroom 302",
          day: "Monday",
          time: "14:00",
          duration: 1,
          slotKeys: ["Monday-14:00"],
          studentCount: 40,
        },
        {
          id: "assign-24",
          courseName: "Digital Electronics",
          faculty: "Prof. Desai",
          sections: ["ECE-B"],
          room: "Classroom 302",
          day: "Wednesday",
          time: "14:00",
          duration: 1,
          slotKeys: ["Wednesday-14:00"],
          studentCount: 40,
        },
        {
          id: "assign-25",
          courseName: "Digital Electronics Lab",
          faculty: "Prof. Desai",
          sections: ["ECE-B"],
          room: "ECE Lab",
          day: "Friday",
          time: "14:00",
          duration: 2,
          slotKeys: ["Friday-14:00"],
          studentCount: 40,
        },
        {
          id: "assign-26",
          courseName: "Signal Processing",
          faculty: "Dr. Verma",
          sections: ["ECE-A"],
          room: "Classroom 302",
          day: "Tuesday",
          time: "14:00",
          duration: 1,
          slotKeys: ["Tuesday-14:00"],
          studentCount: 38,
        },
        {
          id: "assign-27",
          courseName: "Signal Processing",
          faculty: "Dr. Verma",
          sections: ["ECE-A"],
          room: "Classroom 302",
          day: "Thursday",
          time: "14:00",
          duration: 1,
          slotKeys: ["Thursday-14:00"],
          studentCount: 38,
        },
        // Microprocessors Lab - Thursday
        {
          id: "assign-28",
          courseName: "Microprocessors Lab",
          faculty: "Prof. Gupta",
          sections: ["ECE-A"],
          room: "ECE Lab 1",
          day: "Thursday",
          time: "15:00",
          duration: 2,
          slotKeys: ["Thursday-15:00"],
          studentCount: 35,
        },
        // ===== MECHANICAL ENGINEERING =====
        {
          id: "assign-29",
          courseName: "Thermodynamics",
          faculty: "Dr. Reddy",
          sections: ["ME-A", "ME-B"],
          room: "Auditorium B",
          day: "Monday",
          time: "10:00",
          duration: 1,
          slotKeys: ["Monday-10:00"],
          studentCount: 75,
        },
        {
          id: "assign-30",
          courseName: "Thermodynamics",
          faculty: "Dr. Reddy",
          sections: ["ME-A", "ME-B"],
          room: "Auditorium B",
          day: "Tuesday",
          time: "10:00",
          duration: 1,
          slotKeys: ["Tuesday-10:00"],
          studentCount: 75,
        },
        {
          id: "assign-31",
          courseName: "Thermodynamics",
          faculty: "Dr. Reddy",
          sections: ["ME-A", "ME-B"],
          room: "Auditorium B",
          day: "Friday",
          time: "10:00",
          duration: 1,
          slotKeys: ["Friday-10:00"],
          studentCount: 75,
        },
        // Fluid Mechanics - Tuesday afternoon lab
        {
          id: "assign-32",
          courseName: "Fluid Mechanics",
          faculty: "Prof. Kumar",
          sections: ["ME-A"],
          room: "Classroom 303",
          day: "Tuesday",
          time: "14:00",
          duration: 1,
          slotKeys: ["Tuesday-14:00"],
          studentCount: 38,
        },
        {
          id: "assign-33",
          courseName: "Fluid Mechanics Lab",
          faculty: "Prof. Kumar",
          sections: ["ME-A"],
          room: "ME Lab",
          day: "Tuesday",
          time: "15:00",
          duration: 2,
          slotKeys: ["Tuesday-15:00"],
          studentCount: 38,
        },
        // Machine Design
        {
          id: "assign-34",
          courseName: "Machine Design",
          faculty: "Dr. Singh",
          sections: ["ME-B"],
          room: "Classroom 303",
          day: "Monday",
          time: "10:00",
          duration: 1,
          slotKeys: ["Monday-10:00"],
          studentCount: 40,
        },
        {
          id: "assign-35",
          courseName: "Machine Design",
          faculty: "Dr. Singh",
          sections: ["ME-B"],
          room: "Classroom 303",
          day: "Wednesday",
          time: "10:00",
          duration: 1,
          slotKeys: ["Wednesday-10:00"],
          studentCount: 40,
        },
        {
          id: "assign-36",
          courseName: "Machine Design Lab",
          faculty: "Dr. Singh",
          sections: ["ME-B"],
          room: "CAD Lab",
          day: "Friday",
          time: "15:00",
          duration: 2,
          slotKeys: ["Friday-15:00"],
          studentCount: 40,
        },
        // ===== CIVIL ENGINEERING =====
        {
          id: "assign-37",
          courseName: "Structural Analysis",
          faculty: "Dr. Gupta",
          sections: ["CE-A"],
          room: "Classroom 303",
          day: "Tuesday",
          time: "09:00",
          duration: 1,
          slotKeys: ["Tuesday-09:00"],
          studentCount: 35,
        },
        {
          id: "assign-38",
          courseName: "Structural Analysis",
          faculty: "Dr. Gupta",
          sections: ["CE-A"],
          room: "Classroom 303",
          day: "Thursday",
          time: "10:00",
          duration: 1,
          slotKeys: ["Thursday-10:00"],
          studentCount: 35,
        },
        {
          id: "assign-39",
          courseName: "Structural Analysis",
          faculty: "Dr. Gupta",
          sections: ["CE-A"],
          room: "Classroom 303",
          day: "Friday",
          time: "09:00",
          duration: 1,
          slotKeys: ["Friday-09:00"],
          studentCount: 35,
        },
        {
          id: "assign-40",
          courseName: "Surveying & GIS",
          faculty: "Prof. Joshi",
          sections: ["CE-A"],
          room: "Classroom 301",
          day: "Monday",
          time: "14:00",
          duration: 1,
          slotKeys: ["Monday-14:00"],
          studentCount: 32,
        },
        {
          id: "assign-41",
          courseName: "Surveying & GIS Lab",
          faculty: "Prof. Joshi",
          sections: ["CE-A"],
          room: "CE Lab",
          day: "Wednesday",
          time: "15:00",
          duration: 2,
          slotKeys: ["Wednesday-15:00"],
          studentCount: 32,
        },
      ],
    },
    summary: {
      totalAssignments: 41,
      totalStudents: 1273,
      totalClassrooms: 14,
      averageUtilization: 78,
      conflicts: 0,
      constraints: {
        lunchBreakHonored: true,
        preferencesMet: "95%",
        labsAllocated: true,
      },
    },
  };
}

module.exports = { getHackathonDemoSchedule };
